### ISSUE TITLE
Cannot "unpublish" articles from public site

### ISSUE THREAD

**Issue by densho** [densho/encyc-front#51]
Users report:

> On Tue, Jun 7, 2016 at 2:04 PM, Dana Hoshide dana.hoshide@densho.org wrote:
> We noticed in the encyclopedia today that when you search for “Yoshiko Uchida,” one of the results that comes up is “Dummy article 3”: http://encyclopedia.densho.org/Dummy%20article%203/. Looks like an earlier version of the Uchida article. But in the wiki, a search “Dummy article 3” brings up a status 2 article with a different subject.

Examining the version history, it looks like it was published back around March 8:

https://editors.densho.org/index.php?title=Dummy_article_3&oldid=22349

Then un-published a few days later:

https://editors.densho.org/index.php?title=Dummy_article_3&diff=prev&oldid=22387

The document has been deleted from the index; but the raw json is available here:

https://gist.github.com/densho/05eb595660f4f2e94b91b864f1d5a683

**Comment by densho** [comment]
UPDATE: Tried setting the publication status of the article, "Stringtown (detention facility)" from `{{Published}}` to `{{Status3}}`. See: 

https://editors.densho.org/index.php?title=Stringtown_(detention_facility)&diff=prev&oldid=23004

In this case, "unpublishing" seemed to work as expected. The document is still in the ES index (see updated gist: https://gist.github.com/densho/05eb595660f4f2e94b91b864f1d5a683) with `_source.published` set to `false`. 

Not sure what to make of this issue...

**Comment by gjost** [comment]
Working on this.  I'm doing several things:

- [ ] `encyc-front`: Make sureonly display articles where `public == True`.
- [ ] `encyc-core`: Check the logic to make sure the command is not publishing unpublished stuff to ES.
- [ ] `encyc-core`: Actively delete documents that are not marked published.

**Comment by gjost** [comment]
Publishing side starts in `encyc-core:encyc/cli.py`.
