### ISSUE TITLE
ui: Add "we use cookies" notice

### ISSUE THREAD

**Issue by GeoffFroh** [densho/encyc-front#64]
Need a "we use cookies" dismissible banner notice at the bottom of the site. Use bootstrap-compatible code inserted into base.html template

Use js code from https://cookieconsent.insites.com/

**Comment by gjost** [comment]
Note: encycfront uses Bootstrap v2.3.1.

**Comment by GeoffFroh** [comment]
Fixed in 1aef5db6a11b013a3327dfb275bfd29cf191511e on branch `64-hotfix-ui-cookienotice`
