### ISSUE TITLE
Map: urls to facilities with escaped spaces are munged

### ISSUE THREAD

**Issue by GeoffFroh** [densho/encyc-front#70]
Many of the "More Info" urls from the map are malformed. Looks like spaces are being escaped as `%2550` instead of `%20`. Also, some are attempting to link to encyclopedia articles that may not exist.

See, for example: 
https://encyclopedia.densho.org/Crystal_City%2520(detention%2520facility)/

**Comment by GeoffFroh** [comment]
This appears to be a combination of data issues with the backend `facilities.xml` data file and the view code. Currently in `facilities.xml`, the `Location`\`LocationURI` element contains the mediawiki encyclopedia article name (e.g., `San_Francisco%20(detention%20facility)`). 

The code appears to be munging these urls.

**Comment by gjost** [comment]
Fixed by [modifying ansible-colo](https://github.com/densho/ansible-colo/blob/master/encycedit.yml#L255) to install densho-vocab and put symlinks where the old XML files were.
