### ISSUE TITLE
"Next Article" and "Previous Article" links include RG-only articles

### ISSUE THREAD

**Issue by densho** [densho/encyc-front#74]
The "Next Article" and "Previous Article" sidebar links include articles that should appear only in the Resource Guide. See:
https://encyclopedia.densho.org/Korematsu_v._United_States/

"Next Article" link:
https://encyclopedia.densho.org/Korematsu%20v.%20United%20States:%20Japanese-American%20Internment%20(book)/

Background:
ES docs representing articles that should be visible in the Resource Guide, but *not* in `encyc-front` have the attribute `published_encyc = false` and `published_rg = true`

**Comment by gjost** [comment]
Fixed in `encyc-front` commit `a9b785e2d5` for package `encycfront-develop~3.0.0`.
