### ISSUE TITLE
develop: Search page not rendering 

### ISSUE THREAD

**Issue by GeoffFroh** [densho/encyc-front#77]
The Google CSE key (`{{ GOOGLE_CUSTOM_SEARCH_PASSWORD }}`) is missing (set to `REDACTED` actually) in the configs. See:

https://github.com/densho/encyc-front/blob/master/front/front/templates/front/search.html#L29

This appears only to be an issue in the current `develop` package on stage

**Comment by gjost** [comment]
This is fixed now.  I hadn't updated the `/etc/encyc/front-local.cfg` file from Ansible yet.
