### ISSUE TITLE
ui: Fix/replace AddThis sharing button

### ISSUE THREAD

**Issue by GeoffFroh** [densho/encyc-front#86]
It appears that the AddThis sharing button on article pages is no longer functioning correctly. The image is broken and the link now appears to go to a generic AddThis page. Very likely, the current code is not up to date with the most recent version of the official AddThis code.

(It also might be worth investigating alternatives to AddThis, though the analytics are useful)

**Comment by gjost** [comment]
Added the code to the author and article templates.  It looks like the initial `addthis_widget.js` file is loading but I'm not seeing the AddThis buttons on this end.

**Comment by gjost** [comment]
Are there settings in the AddThis account that need to be changed perhaps?

**Comment by GeoffFroh** [comment]
Might be that stage site domain is not part of the account...

**Comment by GeoffFroh** [comment]
Fixed in a4d1894c6c1e4c548f8b02caa61e13f80b1907a1
